# Generated by Django 6.0.3 on 2026-03-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('transferencia', 'Transferência')], default='dinheiro', max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='emprestimos.parcela')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('pagamento', 'Pagamento de Parcela'), ('emprestimo', 'Concessão de Empréstimo'), ('aporte', 'Aporte de Capital'), ('retirada', 'Retirada'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='rotas.caixarota')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
                ('referencia_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.pagamento')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
