# Generated by Django 6.0.3 on 2026-03-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_latitude_cliente_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de credito individual. Se vazio, usa o limite da rota.', max_digits=10, null=True),
        ),
    ]
