# Generated by Django 6.0.3 on 2026-03-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_juros', models.DecimalField(decimal_places=2, help_text='Taxa em % aplicada no momento da criação', max_digits=5)),
                ('num_parcelas', models.PositiveSmallIntegerField()),
                ('periodicidade', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='semanal', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_parcela', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_primeiro_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='rotas.rota')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='emprestimos.emprestimo')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['emprestimo', 'numero'],
                'unique_together': {('emprestimo', 'numero')},
            },
        ),
    ]
