# Generated by Django 6.0.3 on 2026-03-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
