# Generated by Django 6.0.3 on 2026-03-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_juros_padrao', models.DecimalField(decimal_places=2, help_text='Taxa em % por período', max_digits=5)),
                ('periodicidade_padrao', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='semanal', max_length=20)),
                ('num_parcelas_padrao', models.PositiveSmallIntegerField(default=10)),
                ('limite_emprestimo_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Configuração de Rota',
                'verbose_name_plural': 'Configurações de Rotas',
            },
        ),
        migrations.CreateModel(
            name='CaixaRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rota', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caixa', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Caixa da Rota',
                'verbose_name_plural': 'Caixas das Rotas',
            },
        ),
        migrations.CreateModel(
            name='VendedorRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('vinculado_em', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='rotas.rota')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_vinculadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor na Rota',
                'verbose_name_plural': 'Vendedores nas Rotas',
                'unique_together': {('vendedor', 'rota')},
            },
        ),
    ]
