# Generated by Django 6.0.3 on 2026-03-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorota',
            name='juros_mora_dia',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Juros de mora diario em % sobre o valor da parcela', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='configuracaorota',
            name='multa_atraso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multa por atraso em % sobre o valor da parcela', max_digits=5, null=True),
        ),
    ]
